version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
      # Add any other environment variables your application needs
      # - DATABASE_URL=your_database_url
      # - GOOGLE_API_KEY=your_google_api_key  # If you're using Google's AI services
    restart: always
    # Add healthcheck
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3 